### ISSUE TITLE
TypeError when using Gulp 4

### ISSUE THREAD

**Issue by ruvengam** [DerekSeverson/gulp-inject-stringified-html#5]
After updating to Gulp version 4,
I encountered this error when piping through the plugin:
`TypeError: file.pipe is not a function`

In my gulpfile I removed all tasks except `scripts` for debugging,  
and made scripts pipe only to gulp-inject-stringified-html.
 
**gulpfile.js**
```
var gulp = require("gulp");
var injectHtml = require('gulp-inject-stringified-html');
gulp.task("scripts", function(){
    return gulp.src(["../src/js/main.js"])
               //.pipe(errors.logger("File In"))
               .pipe(injectHtml())                    // <--- this!
               .pipe(gulp.dest("public/hello.js"));
 });
```
**main.js**
function sayHello() {
    return { gulp_inject: './template.html' };  // <-- and this!
}

Code tested on gulp 3.9.1 and got the expected results similar to example code.

Error code trace:

```
wp-content\themes\educationcenter\src>gulp scripts
[12:39:48] Using gulpfile wp-content\themes\educationcenter\src\gulpfile.js
[12:39:48] Starting 'scripts'...
[12:39:48] 'scripts' errored after 37 ms
[12:39:48] TypeError: file.pipe is not a function
    at DestroyableTransform._transform (wp-content\themes\educationcenter\src\node_modules\gulp-inject-stringified-html\index.js:33:10)
    at DestroyableTransform.Transform._read (wp-content\themes\educationcenter\src\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (wp-content\themes\educationcenter\src\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (wp-content\themes\educationcenter\src\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (wp-content\themes\educationcenter\src\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (wp-content\themes\educationcenter\src\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at DestroyableTransform.ondata (wp-content\themes\educationcenter\src\node_modules\to-through\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (wp-content\themes\educationcenter\src\node_modules\to-through\node_modules\readable-stream\lib\_stream_readable.js:284:12)
```

P.S.
I was not able to find a working html to js string conversion plugin working good in Gulp 4.
This plugin is a very good solution so I would like to use it.

**Comment by DerekSeverson** [comment]
Hi @ruvengam, 

Thanks for letting me know!  Didn't know gulp was releasing a new version.  

I created a new release candidate which should work with Gulp 4.  
Please install `gulp-inject-stringified-html@2.0.0-alpha.2` or `gulp-inject-stringified-html@next` (same code) and let me know if that fixes things for you.  

After getting your verification, I'll publish it as the official `v2.0.0` designated to work with Gulp 4. 

Best,
Derek
